require ('bootstrap')
require('@fortawesome/fontawesome-free/js/all')
require( '../src/application.scss')
require("@rails/ujs").start()
require("turbolinks").start()
require("@rails/activestorage").start()
require("channels")
require("jquery").start()
require("rails-ujs").start()